# Unix submit description file
# simple Marlin job

executable              = runddsim_QGSP_BERT_TB2022-06_mu-_10GeV_7.sh
log                     = runddsim_QGSP_BERT_TB2022-06_mu-_10GeV_7.log
output                  = outfile_runddsim_QGSP_BERT_TB2022-06_mu-_10GeV_7.txt
error                   = errors_runddsim_QGSP_BERT_TB2022-06_mu-_10GeV_7.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue 1
