# Unix submit description file
# simple Marlin job

executable              = runddsim_QGSP_BERT_TB2022-06_e-_2GeV_3.sh
log                     = runddsim_QGSP_BERT_TB2022-06_e-_2GeV_3.log
output                  = outfile_runddsim_QGSP_BERT_TB2022-06_e-_2GeV_3.txt
error                   = errors_runddsim_QGSP_BERT_TB2022-06_e-_2GeV_3.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue 1
