# Unix submit description file
# simple Marlin job

executable              = runddsim_QGSP_BERT_TB2022-06_proton_2GeV_4.sh
log                     = runddsim_QGSP_BERT_TB2022-06_proton_2GeV_4.log
output                  = outfile_runddsim_QGSP_BERT_TB2022-06_proton_2GeV_4.txt
error                   = errors_runddsim_QGSP_BERT_TB2022-06_proton_2GeV_4.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue 1
