# Unix submit description file                                                                                                                                                                 
# simple Marlin job                                                                                                                                                                            
                                                                                                                                                                                               
executable              = LCIO2build_neutron_10GeV.sh                                                                                                                                                            
log                     = LCIO2build_neutron_10GeV.log                                                                                                                                                      
output                  = outfile_LCIO2build_neutron_10GeV.txt                                                                                                                                              
error                   = errors_LCIO2build_neutron_10GeV.txt                                                                                                                                              
should_transfer_files   = Yes                                                                                                                                                                  
when_to_transfer_output = ON_EXIT                                                                                                                                                              
queue 1                                                                                                                                                                                        
